### ISSUE TITLE
Memory Usage  Increasing Continuously

### ISSUE THREAD

**Issue by krishnachaitanya7** [MishaLaskin/curl#10]
Hi! Great paper btw!
When I run the code the RAM usage continuously increases. I am running the default code with no changes. The memory consumption keeps on increasing and after 8k iterations, the OS kills the process. My PC specs: Intel i7 processor, Nvidia RTX2070 GPU, 16GB RAM. Can you please help me out? Thank you.

**Comment by krishnachaitanya7** [comment]
The memory increases because the replay buffer capacity is large. There is no memory leak or something. It was exceeding my RAM memory hence the process was getting killed. Thank you. Closing the issue now.

**Comment by MishaLaskin** [comment]
got it, thanks!
