### ISSUE TITLE
What is "ema"?

### ISSUE THREAD

**Issue by slerman12** [MishaLaskin/curl#18]
In CURL.encode, what is the arg "ema"?

**Comment by MishaLaskin** [comment]
exponentially moving average of the key encoder

**Comment by slerman12** [comment]
It just occurred to me that query and key have different encoders. Is there a reason for this?

**Comment by MishaLaskin** [comment]
Yes - referring you to MoCo https://arxiv.org/abs/1911.05722 or you could
read the implementation section of the CURL paper
