### ISSUE TITLE
Rainbow DQN + CURL

### ISSUE THREAD

**Issue by seann999** [MishaLaskin/curl#2]
Will there be scripts for discrete/Atari environments?

**Comment by MishaLaskin** [comment]
this was done by @aravindsrinivas in separate codebase (fork of dopamine)

**Comment by aravindsrinivas** [comment]
@seann999 will be released soon

**Comment by MasterScrat** [comment]
I was about to ask the same question. This issue should stay open until a discrete version is available, or maybe this should be mentioned in the README?

**Comment by MishaLaskin** [comment]
done! added note to readme

**Comment by JasonMa2016** [comment]
Any update?

**Comment by aravindsrinivas** [comment]
Code is available at https://github.com/aravindsrinivas/curl_rainbow 
README updated.
Closing issue.
