### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yenchenlin** [MishaLaskin/curl#4]
Hello, I followed the README to run
```bash scripts/run.sh```

This is what I got:
`FileNotFoundError: [Errno 2] No such file or directory: './tmp/cartpole/cartpole-swingup-05-10-im84-b128-s482469-pixel/args.json'`

**Comment by MishaLaskin** [comment]
you have to create the directory `tmp/cartpole`

**Comment by yenchenlin** [comment]
solved, thanks!
