### ISSUE TITLE
WARN precision

### ISSUE THREAD

**Issue by Rivendile** [MishaLaskin/curl#6]
I got **WARN: Box bound precision lowered by casting to float32** when I run the code. Should this be fixed?

**Comment by MishaLaskin** [comment]
Should be ok, I get this warning as well on some machines - the method is
not sensitive to float64 -> 32 casting

**Comment by Rivendile** [comment]
Thanks a lot :)

**Comment by Rivendile** [comment]
Hi, when I run the task "Cheetah, Run", it costs about 65s for every four episodes. Is it ok or did I make some mistakes?
I run the code on TITAN RTX.
The run.sh is:
CUDA_VISIBLE_DEVICES=2 python train.py \
--domain_name cheetah \
--task_name run \
--encoder_type pixel \
--action_repeat 4 \
--save_tb --pre_transform_image_size 100 --image_size 84 \
--work_dir ./tmp \
--agent curl_sac --frame_stack 3 \
--seed -1 --critic_lr 2e-4 --actor_lr 2e-4 --encoder_lr 2e-4 --eval_freq 10000 --batch_size 512 --num_train_steps 100000

**Comment by MishaLaskin** [comment]
That's normal - large batch sizes take a long time to train

**Comment by Rivendile** [comment]
Thanks for your reply!
