### ISSUE TITLE
Is display necessary?

### ISSUE THREAD

**Issue by Rivendile** [MishaLaskin/curl#7]
When I run the code, errors occur.
```
CRITICAL:absl:Shadow framebuffer is not complete, error 0x8cd7
CRITICAL:absl:Could not allocate display lists
CRITICAL:absl:Could not allocate display lists
```
Must I run on the machine with a display? Can the code be changed to go without a display?

**Comment by MishaLaskin** [comment]
that's likely an issue with dm control, would refer to their docs

**Comment by Rivendile** [comment]
That's it. Thx~
